### ISSUE TITLE
Support of sleeping clients

### ISSUE THREAD

**Issue by jpmzometa** [emqtt/emq-sn#28]
In the MQTT-SN protocol specification (Version 1.2), Section 6.14, the support of sleeping clients is described. This is currently not implemented on emq-sn (emqttd-2.2-beta.2). When could I expect this feature?

**Comment by grutabow** [comment]
Developing this feature now. Please be patient since too many TODOs in my list.

**Comment by grutabow** [comment]
@jpmzometa   sleeping device will be added into next official release.

**Comment by jpmzometa** [comment]
Hi. I've been playing around with the sleeping client implementation. It does not work as expected. A client doing a CONNECT to the gateway, SUBSCRIBE to a topic, and DISCONNECT with a duration (i.e. going to sleep) work correctly. However, _every time_ the client sends a PINGREQ (client awake) message, it gets from the gateway _all_ the previous messages that have been published (in the topics subscribed by the client) since the client went to sleep via the DISCONNECT with duration. 

Put in another words, if there are buffered messages for the client in the gateway (that is, for the topics for which the client has subscribed), after a PINGREQ from the client (i.e. client is awake), the gateway should send all buffered messages and at the end a PINGRESP, and the gateway should clear its buffer (assuming all messages satisfied the QoS). If the client sends a new PINGREQ, the gateway should just reply with a PINGRESP if there are no _new_ messages. At the moment, it appears the buffered messages are not cleared in the gateway (i.e. each new message is added to the buffer, and all messages in the buffer are sent to the client every time a PINGREQ arrives from the client).

**Comment by grutabow** [comment]
@jpmzometa  This bug has been fixed in v2.3-beta1.
