### ISSUE TITLE
QoS granted on SUBACK is ignored 

### ISSUE THREAD

**Issue by jpmzometa** [emqtt/emq-sn#42]
When a client SUBSCRIBE to a topic, it can specify a QoS, and the gateway replies with a SUBACK specifying the granted QoS. However, the granted QoS for a subscribed topic is ignored by the gateway afterwards. The QoS of the subscribed topic at any given time seems to be determined by the QoS set on the PUBLISH message by e.g. another client.

**Comment by grutabow** [comment]
What's your SUBSCRIBE Qos? and what is PUBLISH Qos? The min Qos should be picked.

MQTT v3.1.1 says

> The Server might grant a lower 983 maximum QoS than the subscriber requested. The QoS of Payload Messages sent in response to a 984 Subscription MUST be the minimum of the QoS of the originally published message and the maximum 985 QoS granted by the Server.

**Comment by jpmzometa** [comment]
Ok, got it. It works as you describe it. The subscribing client was using QoS=2 by default.
