### ISSUE TITLE
UNSUBSCRIBE without a payload disconnects the client

### ISSUE THREAD

**Issue by jpmzometa** [emqtt/emq-sn#50]
Due to an error, a connected client sent an UNSUBSCRIBE without a payload to the MQTT-SN gateway. I notice that the client is disconnected immediately after without any notification.

**Comment by grutabow** [comment]
"an UNSUBSCRIBE without a payload" means an UNSUBSCRIBE without TopicId? This UNSUBSCRIBE is not a complete MQTT-SN packet, right? If it is true, emq-sn would be confused of the incoming packet and false-interpret this packet and next packet. If fortunate enough, it can recover from such an error.

**Comment by jpmzometa** [comment]
Yes, it is an invalid/incomplete packet. The problem is that the gateway _immediately_ loses/closes the connection with the client (but without an DISCONNECT acknowledgement).

**Comment by grutabow** [comment]
MQTT-SN spec does not state how to handle an invalid packet. But MQTT spec has addressed that

> Unless stated otherwise, if either the Server or Client encounters a protocol violation, it MUST close the
Network Connection on which it received that Control Packet which caused the protocol violation.

So it is reasonable to close connection without a notification in this case.

What do you think about it?

**Comment by jpmzometa** [comment]
I think it's fine. I wasn't sure if that was the intended behaviour or some kind of internal problem in the plugin.  Thanks for the clarification.
