### ISSUE TITLE
CONNACK is not always sent to the client

### ISSUE THREAD

**Issue by jpmzometa** [emqtt/emq-sn#67]
I found a strange behaviour on the MQTT-SN plugin. If a client sends a CONNECT request twice in a row, a CONNACK is send every other time (see attached file). For example:
CONNECT (client -> gateway)
CONNACK (gateway -> client)
CONNECT (client -> gateway)
(here the expected CONNACK is not sent)
CONNECT (client -> gateway)
CONNACK (gateway -> client)

Note that this only happens if the client uses the same source port (9977 in the attached file).

![screen shot 2018-01-16 at 17 12 21](https://user-images.githubusercontent.com/2261366/34999573-5acc0418-fae2-11e7-87d0-1ef671dc8111.png)

**Comment by justina111** [comment]
Which version did you use?

**Comment by jpmzometa** [comment]
I'm using the latest 2.3.3.

**Comment by justina111** [comment]
@jpmzometa Please update the newest master branch, the PR #69 has already resolve this problem.

**Comment by emqplus** [comment]
@jpmzometa close the issue.
