### ISSUE TITLE
Feature request: Wildcards

### ISSUE THREAD

**Issue by jpmzometa** [emqtt/emq-sn#74]
Hi, this is a feature request. Could you implement support for wildcards (single level + and multilever #)? :)

**Comment by grutabow** [comment]
It is allowed to have '+' and '#' in subscription topic.

**Comment by grutabow** [comment]
Your are right. From the view of client, broker should destroy all the registered topic since clean-session is true. Please be patient for the fix.

**Comment by emqplus** [comment]
@jpmzometa The issues has been fixed in v2.3.5.
